-- Videos the user deleted from the episode list must never be re-imported by
-- the YouTube channel sync. Deleting an episode records its video id here, and
-- /api/youtube/sync skips every id in this table.

create table if not exists sync_exclusions (
  video_id text primary key,
  created_at timestamptz not null default now()
);

alter table sync_exclusions enable row level security;
drop policy if exists "authenticated full access" on sync_exclusions;
create policy "authenticated full access" on sync_exclusions
  for all to authenticated using (true) with check (true);

-- Seed: the 112 episodes deleted on 2026-07-22 must never come back.
insert into sync_exclusions (video_id) values
  ('CH98uZK9Udc'),
  ('wlcQ77ohYkA'),
  ('h13ZucC_gRM'),
  ('3jeWqZ7CT58'),
  ('k7LE3IGtMQE'),
  ('QjiSnYti4NM'),
  ('iC8cF9VB9aM'),
  ('O3op-E8Qz4Y'),
  ('FCoMhzqSVHo'),
  ('SnISHRb91Hc'),
  ('Z3Dtb0kld74'),
  ('cm3g-IeqJOI'),
  ('lI0oxE5bOlQ'),
  ('lxGenQLM7Po'),
  ('3uCVj2DOpMM'),
  ('Fx1XE6iMfbI'),
  ('FCvzJI1DXfc'),
  ('9f5bnI20pNw'),
  ('v-Ohm11-Bcs'),
  ('2rkmLGdgRes'),
  ('Riq4ngME1XM'),
  ('lq4jXzMiqq4'),
  ('PtFspczrQ9Y'),
  ('nWJF-XCXvzU'),
  ('7CooX2TRIyM'),
  ('Xi3DnSJ7PGM'),
  ('TESk4Q6_FFs'),
  ('tHCl5twLljs'),
  ('kMKHsiH-iCY'),
  ('dG7je6O38dw'),
  ('qFmXeqLaoCE'),
  ('acSOH2ucrAc'),
  ('fwfAahhfbR0'),
  ('tfBh_HpwFg0'),
  ('E_caxYmtcO4'),
  ('RoPw8EOw8FA'),
  ('f9v54JL1_qA'),
  ('DwXhtCtPbio'),
  ('aQPzy0xQn_4'),
  ('XThHDG1OvWY'),
  ('34jEh896dAg'),
  ('SbEiVEojnj0'),
  ('AopZUihuEzo'),
  ('OSiokoJI69c'),
  ('5d3ho9ylklg'),
  ('jnuC3dJy8-I'),
  ('3PAUMUVODs8'),
  ('UZnq3OcSi1s'),
  ('3egHBYVas4o'),
  ('En8Q0h4t7Ks'),
  ('y9hNWg_Ms24'),
  ('FMOq4PVkx1U'),
  ('AwqPhRN1ORk'),
  ('HaA_saOd6P0'),
  ('pDEUXbvG50c'),
  ('RFPOa4_Mpyg'),
  ('gLJMnHz6xbU'),
  ('r4BZ3mjLjg0'),
  ('lWyOu1JMg8Q'),
  ('x9wzJXAZhsw'),
  ('y2eORuYL18Y'),
  ('u9_cVulR-_I'),
  ('ADky1p1X-IM'),
  ('S1XgatgZyrc'),
  ('X8lVFiD1Syg'),
  ('eCmWcH0eNow'),
  ('8zv_PRyVOt0'),
  ('G7iZde3fa5o'),
  ('KCcV7Szy4gU'),
  ('9xT6vfeRLx4'),
  ('ZDWhtGj8l5s'),
  ('mBmYpVu-7LA'),
  ('rz5QqeLUks8'),
  ('FAayeoBW7HM'),
  ('ocD6-v2rQDc'),
  ('FgcSmdmLvNM'),
  ('yJA1_uwY-Xw'),
  ('hDtTvTs9Xg0'),
  ('_XLlZDKls-I'),
  ('Kau4W3DxFGg'),
  ('m5Df7D2Jms0'),
  ('9Yk5T2e0Kg4'),
  ('Gd4LNtibCIo'),
  ('ooyq0ot4prU'),
  ('KBYUCepCdrc'),
  ('yGLkwxQ-y1o'),
  ('-mo0BU-XTEI'),
  ('woHNXISKo0k'),
  ('F3i2Z4wJJJ4'),
  ('cM2QA0zwSkk'),
  ('k_sjppMXXMk'),
  ('mk00jiHOZZg'),
  ('787paXffH7o'),
  ('u5JN63MbOK8'),
  ('AH8ZjqCwTDg'),
  ('Wzpr4KBNcQY'),
  ('nKydiz032tQ'),
  ('NqJH5MBE6nc'),
  ('bz5Oe2HvS8M'),
  ('llC9cILj_S4'),
  ('F61zadTb3NI'),
  ('Nj2B028fpC8'),
  ('0yrQkYUS0j4'),
  ('QSotEeefmYU'),
  ('oCPqUV5f5IE'),
  ('k7698bAQWzs'),
  ('DUBzZhrScT8'),
  ('ag6GLJ0hsZw'),
  ('K3n4DRUrFkc'),
  ('BxT_TCZmQz0'),
  ('f2AxBuBQRKA'),
  ('_1Czhp7oPww')
on conflict (video_id) do nothing;
